### ISSUE TITLE
How to build NextCraft for MacOS

### ISSUE THREAD

**Issue by githubcraft** [Twometer/NextCraft#1]
Hi!
Can NextCraft build on MacOS and play? 
Thank you

**Comment by Twometer** [comment]
Hi,
currently it only runs on Windows. This is because some parts of the client are using the Win32 APIs (e.g. the [Tcp Client](https://github.com/Twometer/NextCraft/blob/master/src/net/TcpClient.h) uses Winsock).
Generally, it should run because OpenGL is platform independent, but it'd be some work to port the non-GL code

**Comment by githubcraft** [comment]
If you have some time please update it to support multi platform, so that we can easy to test!
Thank you

**Comment by Twometer** [comment]
If I find some time, I can try to do that. However the only macOS device I have access to is from 2009 which is probably not fast enough to develop and test a Minecraft-like game.

**Comment by Twometer** [comment]
The main things that probably need to be changed is the [threading stuff](https://github.com/Twometer/NextCraft/blob/master/src/mesh/AsyncMeshBuilder.cpp) and the [TCP stuff](https://github.com/Twometer/NextCraft/blob/master/src/net/TcpClient.cpp), so if you have a faster Mac and would like to try and add support for mac, feel free to submit a PR ;-)

**Comment by githubcraft** [comment]
@Twometer OK I will try
 - Please help me document on how to build code on MacOS?
- As I see is the source code C++?
- What is the library or source code that can replace the Threading Stuff and TCP stuff that we can build on both win and mac?

**Comment by Twometer** [comment]
- The code can be built using CMake. Make sure that you clone the repository with `--recurse-submodules` to get all the libraries from Git.
- Yes, the source code is in C++
- I think threading can stay since I used posix threads using MinGW under windows. However, TCP is currently implemented using the Winsock API. A new implementation has to be made which uses the BSD Socket API.

**Comment by githubcraft** [comment]
Hi @Twometer 
With your help I can now setup the env and compile, as you guess, there is error with TcpClient.h
I now will try to correct the TCP stuff if i can ...
If you have detail document on  BSD Socket API that can apply to our code, please post, I can try to understand.
Thank you!!!
![image](https://user-images.githubusercontent.com/83824252/122962271-70caab80-d3af-11eb-8b2f-6259a9c788f1.png)

**Comment by Twometer** [comment]
The BSD Socket API is just a fancy name for the standard C library for sockets - Any resource on the internet can probably explain that better than I can :-)
You can just google `C++ sockets macOS` or maybe try [this](https://www.geeksforgeeks.org/socket-programming-cc/) tutorial.

**Comment by Twometer** [comment]
BTW, to not break compatibility with windows, you should use `#ifdef`s around the relevant changes, so that the preprocessor selects the right implementation depending on the OS, for example:

```cpp
#ifdef _WIN32
#include <winsock2.h>
#else
#include <sys/socket.h>
#endif
```

If you're interested, a list of all OS constants you can use can be found [here](https://stackoverflow.com/a/22622250/7702748)

**Comment by githubcraft** [comment]
Sure! I will try not to break your code on Window platform!

**Comment by githubcraft** [comment]
Hi @Twometer 
I am on the way custom the TCP code. What is your current IDE when working with NextCraft and C++
What is your project cppStandard. I am have some problem with intelliSense of Visual Studio Code on MacOS


![image](https://user-images.githubusercontent.com/83824252/123104764-6ff25200-d461-11eb-9d77-134b3d52700a.png)

**Comment by Twometer** [comment]
Hi, 
nice to hear that  it's making progress :-)
I am working with JetBrains CLion.
As you can also see in `CMakeLists.txt`, NextCraft is currently using C++ 14.

**Comment by githubcraft** [comment]
@Twometer Do you have Discord or Telegram, or any other message client, can we make a channel to direct message 
Thank you so much!

**Comment by Twometer** [comment]
if you like you can add me on Discord, my tag is `Twometer#6969`

**Comment by githubcraft** [comment]
@Twometer I am trying to test TCP code,
Now I have another error here
NextCraft/lib/mingw_stdthreads/mingw.mutex.h:46:10: fatal error: 'sdkddkver.h' file not found

**Comment by Twometer** [comment]
Oh... My version of mingw did not have support for `std::thread` and the like, and therefore I used a compatibility library which adds this. However, on your machine you don't have mingw, which is why it probably fails to build. You'd probably need to update the  CMakeLists.txt file so that it does not try to build/link that support library on non-windows systems. You can do that in CMake with
```cmake
if(WIN32)
  # windows-only stuff here
endif()
```
( from: https://stackoverflow.com/a/40217291/7702748 )

**Comment by githubcraft** [comment]
Hi @Twometer 
I slowly go to this error :)

ld: library not found for -lWs2_32.lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)

C++ and Cmake stuffs quite new to me so I can not do it myself, sorry for asking you step by step...

```
cmake_minimum_required(VERSION 3.14)
project(NextCraft)

set(CMAKE_CXX_STANDARD 14)

add_subdirectory(lib/glfw)
add_subdirectory(lib/json)
add_subdirectory(lib/CrystalUI)

option(MINGW_STDTHREADS_GENERATE_STDHEADERS "" ON)
if(WIN32)
add_subdirectory(lib/mingw_stdthreads)
endif()
add_definitions(-D_WIN32_WINNT=0x0600)

add_executable(NextCraft
        src/net/TcpClient.cpp
        src/net/McClient.cpp
        src/net/McBuffer.cpp
        src/net/NetUtils.cpp
        src/net/chat/ChatParser.cpp
        src/util/ZLib.cpp
        src/util/Logger.cpp
        src/util/FloatBuffer.cpp
        src/model/world/Chunk.cpp
        src/model/world/World.cpp
        src/model/world/Section.cpp
        src/model/world/BlockData.cpp
        src/model/world/AABB.cpp
        src/model/block/BlockRegistry.cpp
        src/model/player/Player.cpp
        src/render/Camera.cpp
        src/render/GameRenderer.cpp
        src/render/shaders/IShader.cpp
        src/render/block/IBlockRenderer.cpp
        src/render/block/DefaultBlockRenderer.cpp
        src/render/block/PlantRenderer.cpp
        src/render/block/LeavesRenderer.cpp
        src/render/block/FluidRenderer.cpp
        src/render/HighlightRenderer.cpp
        src/input/InputHandler.cpp
        src/input/Raycast.cpp
        src/gui/GuiHandler.cpp
        src/gui/MainMenuScreen.cpp
        src/mesh/AsyncMeshBuilder.cpp
        src/mesh/SectionMesh.cpp
        src/mesh/Mesh.cpp
        src/gl/Loader.cpp
        src/gl/Vao.cpp
        src/NextCraft.cpp
        src/main.cpp
        lib/glad/glad.c
        lib/spng/spng.c)

target_include_directories(NextCraft PRIVATE lib/glm lib/glfw/include inc lib/CrystalUI/src lib/CrystalUI/inc lib/concurrentqueue lib/glad/include lib/spng)
target_link_libraries(NextCraft CrystalUI glfw ${GLFW_LIBRARIES} nlohmann_json::nlohmann_json Ws2_32.lib z.lib mingw_stdthreads)
```

**Comment by Twometer** [comment]
No Problem :)
I think the issue here is that you're still linking against `Ws2_32.lib`, which is the WinSock library that we are not using on Mac. You should also use a windows-specific if statement around the `target_link_libraries`.
In the non-windows version, I think we should also leave out `mingw_stdthreads` since we no longer build that library

**Comment by githubcraft** [comment]
Hi @Twometer 
After remove lWs2_32.lib and lz.lib due to error library not found, I come to error Undefined symbols for architecture x86_64


```
ld: library not found for -lWs2_32.lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)



ld: library not found for -lz.lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## To fix aboove message, on MacOS we will have
## target_link_libraries(NextCraft CrystalUI glfw ${GLFW_LIBRARIES} nlohmann_json::nlohmann_json)

## ----> Now we are here

Undefined symbols for architecture x86_64:
  "TcpClient::Send(unsigned char*, int)", referenced from:
      McClient::SendPacket(int, McBuffer&) in McClient.cpp.o
  "TcpClient::Close()", referenced from:
      McClient::Connect(char const*, char const*, unsigned short) in McClient.cpp.o
  "TcpClient::Connect(char const*, unsigned short)", referenced from:
      McClient::Connect(char const*, char const*, unsigned short) in McClient.cpp.o
  "TcpClient::Receive(unsigned char*, int)", referenced from:
      McClient::Connect(char const*, char const*, unsigned short) in McClient.cpp.o
  "TcpClient::ReadByte()", referenced from:
      McClient::ReadVarInt() in McClient.cpp.o
  "_crc32", referenced from:
      _read_header in spng.c.o
      _read_chunk_bytes in spng.c.o
      _read_chunks_before_idat in spng.c.o
  "_inflate", referenced from:
      ZLib::Decompress(unsigned char*, int, unsigned char*, int) in ZLib.cpp.o
      _read_scanline_bytes in spng.c.o
  "_inflateEnd", referenced from:
      ZLib::Decompress(unsigned char*, int, unsigned char*, int) in ZLib.cpp.o
      _spng_decode_image in spng.c.o
  "_inflateInit_", referenced from:
      ZLib::Decompress(unsigned char*, int, unsigned char*, int) in ZLib.cpp.o
      _spng_decode_image in spng.c.o
  "_inflateValidate", referenced from:
      _spng_decode_image in spng.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [NextCraft] Error 1
make[2]: *** [CMakeFiles/NextCraft.dir/all] Error 2
make[1]: *** [CMakeFiles/NextCraft.dir/rule] Error 2
make: *** [NextCraft] Error 2

```

**Comment by Twometer** [comment]
z.lib is required for NextCraft. You have to install that library on your computer

**Comment by githubcraft** [comment]
I just install zlib and I think the code can understand zlib
![image](https://user-images.githubusercontent.com/83824252/123676452-272a0700-d86e-11eb-8f56-ced98e4868a0.png)


I think I must change z.lib to something but I can not find yet
My current target_link_libraries
target_link_libraries(NextCraft CrystalUI glfw ${GLFW_LIBRARIES} nlohmann_json::nlohmann_json z.lib)

```
ld: library not found for -lz.lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [NextCraft] Error 1
make[2]: *** [CMakeFiles/NextCraft.dir/all] Error 2
make[1]: *** [CMakeFiles/NextCraft.dir/rule] Error 2
make: *** [NextCraft] Error 2
```

**Comment by Twometer** [comment]
I think on unix-like systems, it is just  `-lz`
Try just `z` as the name in cmake

**Comment by githubcraft** [comment]
Ah ok so we only put "z" to target_link_libraries
Now the error is about x86_64, Maybe i must reimplement the detail code of TcpClient?
```
Undefined symbols for architecture x86_64:
  "TcpClient::Send(unsigned char*, int)", referenced from:
      McClient::SendPacket(int, McBuffer&) in McClient.cpp.o
  "TcpClient::Close()", referenced from:
      McClient::Connect(char const*, char const*, unsigned short) in McClient.cpp.o
  "TcpClient::Connect(char const*, unsigned short)", referenced from:
      McClient::Connect(char const*, char const*, unsigned short) in McClient.cpp.o
  "TcpClient::Receive(unsigned char*, int)", referenced from:
      McClient::Connect(char const*, char const*, unsigned short) in McClient.cpp.o
  "TcpClient::ReadByte()", referenced from:
      McClient::ReadVarInt() in McClient.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [NextCraft] Error 1
make[2]: *** [CMakeFiles/NextCraft.dir/all] Error 2
make[1]: *** [CMakeFiles/NextCraft.dir/rule] Error 2
make: *** [NextCraft] Error 2

```

**Comment by Twometer** [comment]
Did you accidently remove TcpClient.cpp from the build? because it should actually  work now

**Comment by githubcraft** [comment]
Hi @Twometer 
Thank you very much, with your help step by step
Now i can create tcp socket, connect and login to the server
But when loading assets, I have error like bellow
```
[Info] Initializing mesh builder queue
Status: 0
Connected to 127.0.0.1
[Info] Login completed
[Debug] Loading image assets/fonts/nirmala.png
NextCraft(5385,0x116359e00) malloc: can't allocate region
:*** mach_vm_map(size=140735348928512, flags: 100) failed (error code=3)
NextCraft(5385,0x116359e00) malloc: *** set a breakpoint in malloc_error_break to debug
libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Signal: SIGABRT (signal SIGABRT)

```

**Comment by Twometer** [comment]
You probably don't have the assets folder in path. Try setting the working directory of the app to the main directory, or copying the assets folder to t he output folder.

**Comment by githubcraft** [comment]
@Twometer Awesome!
I now can see the GUI but can not click into any buttons

```
[Info] Initializing mesh builder queue
Status: 0
Connected to 127.0.0.1
[Debug] Loading image assets/fonts/nirmala.png
INFO: Loading shader
INFO: Loading shader
INFO: Loading shader
[Debug] Loading shader assets/shaders/terrain.v.glsl // assets/shaders/terrain.f.glsl
[Debug] Loading shader assets/shaders/highlight.v.glsl // assets/shaders/highlight.f.glsl
[Debug] Loading image assets/textures/atlas_blocks.png
[Info] Login completed

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

![image](https://user-images.githubusercontent.com/83824252/123812301-2d77bc00-d91e-11eb-89bf-47850881dd9b.png)

![image](https://user-images.githubusercontent.com/83824252/123811893-dbcf3180-d91d-11eb-9e8e-da4e8e931d48.png)

**Comment by githubcraft** [comment]
Achievement unlock
First blood by Zombie :)))

```
[21:08:13 INFO]: DevClient[/127.0.0.1:53314] logged in with entity id 343 at (24.5, 69.0, 245.5)
[21:08:13 INFO]: DevClient joined the game
[21:08:43 INFO]: DevClient was slain by Zombie

```

**Comment by Twometer** [comment]
Hey, that's really cool that you got it running! 🥳 

As for the buttons. I don't know why they don't work but what you can try  is setting a breakpoint [here](https://github.com/Twometer/NextCraft/blob/master/src/NextCraft.cpp#L84) and see if GLFW receives the button click. That can tell us if it is a bug with the Gui library.

**Comment by githubcraft** [comment]
I found that this function calculate wrong when the window on the iMac screen
```
void Component::on_mouse_down(glm::vec2 vec) {
        if (is_inside(vec))
            isMouseDown = true;
    }

```
I switch the screen to the extend desktop then the function works and button can click and i can now join the game!

The screen also "eating" my mouse so that I can not esc to get the mouse back.

But hey, thank you so much for help me getting start with this project.
I can now start learning more about C++ and this awesome project!

![image](https://user-images.githubusercontent.com/83824252/123994664-cb8b8500-d9f7-11eb-9d78-1c6b158ba31e.png)

**Comment by githubcraft** [comment]
I am also creating PR for the change, please check if you can use the code
Thank you!
![image](https://user-images.githubusercontent.com/83824252/123996651-bdd6ff00-d9f9-11eb-83a7-dd257b32716e.png)

**Comment by Twometer** [comment]
Yeah I know, it currently eats the mouse. On Windows I used to Alt+Tab out of the window.
The misdetection of clicks may be related to a high-DPI screen on your Mac, I'll look into it when I have the time

**Comment by Twometer** [comment]
As for the PRs, the fixes look nice. However, you've somehow made it on three branches and split it on three PRs...? Normally one only makes a single PR with all your commits in it.

Maybe you can merge your branches together, and then make one Pull Request. That would make it easier for me to test and review the code before merging it into master :)

**Comment by githubcraft** [comment]
Hi @Twometer I only use the Github web to create PRs so some how it is very complicated.
I just try to merge and make new PR, please check!
Thank you very much!

**Comment by Twometer** [comment]
Ah yes that's much better, thank you!
